import { OrderStatusCode } from "../request/GetOrderRequest";

export interface OrderInfoDetailItem {
  order_detail_id: number,
  product_id: number,
  product_name: string,
  product_desc_pdp: string,
  product_desc_atc: string,
  product_price: number,
  subtotal_price: number,
  weight: number,
  total_weight: number,
  quantity: number,
  quantity_deliver: number,
  quantity_reject: number,
  is_free_returns: boolean,
  insurance_price: number,
  normal_price: number,
  currency_id: number,
  currency_rate: number,
  min_order: number,
  child_cat_id: number,
  campaign_id: string,
  product_picture: string,
  snapshot_url: string,
}

export interface OrderHistoryItem {
  action_by: string,
  hist_status_code: number,
  message: string,
  timestamp: string,
  comment: string,
  create_by: number,
  update_by: string
}

export default interface GetSingleOrderResponse {
  order_id: number,
  buyer_id: number,
  seller_id: number,
  payment_id: number,
  is_affiliate: boolean,
  is_fulfillment: boolean,
  order_warehouse: {
    warehouse_id: number,
    fulfill_by: number,
    meta_data: {
      warehouse_id: number,
      partner_id: number,
      shop_id: number,
      warehouse_name: string,
      district_id: number,
      district_name: string,
      city_id: number,
      city_name: string,
      province_id: number,
      province_name: string,
      status: number,
      postal_code: string,
      is_default: number,
      latlon: string,
      latitude: string,
      longitude: string,
      email: string,
      address_detail: string,
      country_name: string,
      is_fulfillment: boolean
    }
  },
  order_status: OrderStatusCode,
  invoice_number: string,
  invoice_pdf: string,
  invoice_url: string,
  open_amt: number,
  lp_amt: number,
  cashback_amt: number,
  info: string,
  comment: string,
  item_price: number,
  buyer_info: {
    buyer_id: number,
    buyer_fullname: string,
    buyer_email: string,
    buyer_phone: string
  },
  shop_info: {
    shop_owner_id: number,
    shop_owner_email: string,
    shop_owner_phone: string,
    shop_name: string,
    shop_domain: string,
    shop_id: number
  },
  shipment_fulfillment: {
    id: number,
    order_id: number,
    payment_date_time: string,
    is_same_day: boolean,
    accept_deadline: string,
    confirm_shipping_deadline: string,
    item_delivered_deadline: {
      Time: string,
      Valid: boolean
    },
    is_accepted: boolean,
    is_confirm_shipping: boolean,
    is_item_delivered: boolean,
    fulfillment_status: number
  },
  preorder: {
    order_id: number,
    preorder_type: number,
    preorder_process_time: number,
    preorder_process_start: string,
    preorder_deadline: string,
    shop_id: number,
    customer_id: number
  },
  order_info: {
    order_detail: OrderInfoDetailItem[],
    order_history: OrderHistoryItem[],
      order_age_day: number,
      shipping_age_day: number,
      delivered_age_day: number,
      partial_process: boolean,
      shipping_info: {
        sp_id: number,
        shipping_id: number,
        logistic_name: string,
        logistic_service: string,
        shipping_price: number,
        shipping_price_rate: number,
        shipping_fee: number,
        insurance_price: number,
        fee: number,
        is_change_courier: boolean,
        second_sp_id: number,
        second_shipping_id: number,
        second_logistic_name: string,
        second_logistic_service: string,
        second_agency_fee: number,
        second_insurance: number,
        second_rate: number,
        awb: string,
        autoresi_cashless_status: number,
        autoresi_awb: string,
        autoresi_shipping_price: number,
        count_awb: number,
        isCashless: boolean,
        is_fake_delivery: boolean
      },
      destination: {
        receiver_name: string,
        receiver_phone: string,
        address_street: string,
        address_district: string,
        address_city: string,
        address_province: string,
        address_postal: string,
        customer_address_id: number,
        district_id: number,
        city_id: number,
        province_id: number
      },
      is_replacement: boolean,
      replacement_multiplier: number
  },
  origin_info: {
      sender_name: string,
      origin_province: number,
      origin_province_name: string,
      origin_city: number,
      origin_city_name: string,
      origin_address: string,
      origin_district: number,
      origin_district_name: string,
      origin_postal_code: string,
      origin_geo: string,
      receiver_name: string,
      destination_address: string,
      destination_province: number,
      destination_city: number,
      destination_district: number,
      destination_postal_code: string,
      destination_geo: string,
      destination_loc: {
        lat: number,
        lon: number
      }
  },
  payment_info: {
    payment_id: number,
    payment_ref_num: string,
    payment_date: string,
    payment_method: number,
    payment_status: string,
    payment_status_id: number,
    create_time: string,
    pg_id: number,
    gateway_name: string,
    discount_amount: number,
    voucher_code: string,
    voucher_id: number
  },
  insurance_info: {
    insurance_type: 0
  },
  hold_info: null|any,
  cancel_request_info: null|any,
  create_time: string,
  shipping_date: null|any,
  update_time: string,
  payment_date: string,
  delivered_date: null|any,
  est_shipping_date: null|any,
  est_delivery_date: null|any,
  related_invoices: null|any,
  custom_fields: null|any
}